import img1 from "./assets/Productos/a1.png";
const datos = [
  {
    id: 1,
    producto: "Aire Acondiconado",
    nombre: "SPLIT DECORATIVO PARED",
    descripcion: " esto es algo y asi ",
    img: { img1 },
  },
  {
    id: 2,
    producto: "Aire Acondiconado",
    nombre: "SPLIT DECORATIVO PISO-TECHO",
    descripcion: " esto es algo y asi ",
    img: "../src/assets/Productos/a2.png",
  },
  {
    id: 3,
    producto: "Aire Acondiconado",
    nombre: "CASSETTE",
    descripcion: " esto es algo y asi ",
    img: "../src/assets/Productos/a3.png",
  },
  {
    id: 4,
    producto: "Aire Acondiconado",
    nombre: "SPLIT DUCTO",
    descripcion: " esto es algo y asi ",
    img: "../src/assets/Productos/a4.png",
  },
  {
    id: 5,
    producto: "Aire Acondiconado",
    nombre: "VRF / MULTI V / VRV",
    descripcion: " esto es algo y asi ",
    img: "../src/assets/Productos/a5.png",
  },
  {
    id: 6,
    producto: "Aire Acondiconado",
    nombre: "CHILLER",
    descripcion: " esto es algo y asi ",
    img: "../src/assets/Productos/a6.png",
  },
  {
    id: 7,
    producto: "Aire Acondiconado",
    nombre: "Mini VRF /VRV /MULTISPLIT",
    descripcion: " esto es algo y asi ",
    img: "../src/assets/Productos/a7.png",
  },
  {
    id: 8,
    producto: "Aire Acondiconado",
    nombre: "PAQUETE (ROOFTOP)",
    descripcion: " esto es algo y asi ",
    img: "../src/assets/Productos/a8.png",
  },
  {
    id: 9,
    producto: "Aire Acondiconado",
    nombre: "FAN COIL AGUA HELADA",
    descripcion: " esto es algo y asi ",
    img: "../src/assets/Productos/a9.png",
  },
  {
    id: 10,
    producto: "Anclaje",
    nombre: "TORNILLO AUTOPERFORANTE",
    descripcion: " esto es algo y asi ",
    img: "../src/assets/Productos/",
  },
  {
    id: 11,
    producto: "Anclaje",
    nombre: "BASE DE PISO PARA CONDENSADORA",
    descripcion: " esto es algo y asi ",
    img: "../src/assets/Productos/",
  },
  {
    id: 12,
    producto: "Anclaje",
    nombre: "BROCAS METÁLICAS",
    descripcion: " esto es algo y asi ",
    img: "../src/assets/Productos/",
  },
  {
    id: 13,
    producto: "Anclaje",
    nombre: "JUEGO DE EXPANDIDORES",
    descripcion: " esto es algo y asi ",
    img: "../src/assets/Productos/",
  },
  {
    id: 14,
    producto: "Anclaje",
    nombre: "SOPORTE PARA CONDENSADORA",
    descripcion: " esto es algo y asi ",
    img: "../src/assets/Productos/",
  },
  {
    id: 15,
    producto: "Anclaje",
    nombre: "ABOCARDADO",
    descripcion: " esto es algo y asi ",
    img: "../src/assets/Productos/",
  },
  {
    id: 16,
    producto: "Anclaje",
    nombre: "ANCLAJE MARIPOSA",
    descripcion: " esto es algo y asi ",
    img: "../src/assets/Productos/",
  },
  {
    id: 17,
    producto: "Anclaje",
    nombre: "RIEL STRUT",
    descripcion: " esto es algo y asi ",
    img: "../src/assets/Productos/",
  },
  {
    id: 18,
    producto: "Anclaje",
    nombre: "TUERCAS",
    descripcion: " esto es algo y asi ",
    img: "../src/assets/Productos/",
  },
];
export default datos;
